### ISSUE TITLE
Any way to make multiple streaming URL

### ISSUE THREAD

**Issue by hupptechnologies** [ssnat/GoFM#1]
Hello, @pxgo 

Is there any way to create multiple streaming URL ?
Example: 

Different songs play for the each different URL from different folder. So basically kind of the dynamic URL & based on that songs play for each URL.

**Comment by pxgo** [comment]
> Hello, @pxgo
> 
> Is there any way to create multiple streaming URL ? Example:
> 
> Different songs play for the each different URL from different folder. So basically kind of the dynamic URL & based on that songs play for each URL.

Sorry for the delay in response and thank you for your interest in using my GoFM project. At the inception of the project, I did not plan to develop the feature you are looking for to maintain a minimalist approach. However, you can currently achieve the same goal by deploying multiple GoFM services and using NGINX's reverse proxy. I will seriously consider adding this feature to GoFM when I have time. If you have any good ideas or suggestions, please feel free to submit a PR.
